<?php

use App\Http\Requests\StoreOrderRequest;
use Illuminate\Translation\Translator;
use Illuminate\Validation\Validator;

test('validation pass with correct data', function (array $data, bool $valid) {

    $translator = $this->createMock(Translator::class);
    $request = new StoreOrderRequest();
    $validator = new Validator($translator, $data, $request->rules());

    expect($validator->passes())->toBe($valid);
})->with(
    function () {
        return
            [
                'with full data' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => 'Test@email.it',
                        'country' => 'Test',
                        'address' => 'Test',
                        'phone' => '080808080',
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => true,
                ],

                'without company_email' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => null,
                        'country' => 'Test',
                        'address' => 'Test',
                        'phone' => '080808080',
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without company_country' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => 'Test@email.it',
                        'country' => null,
                        'address' => 'Test',
                        'phone' => '080808080',
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without company_phone' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => 'Test@email.it',
                        'country' => 'Test',
                        'address' => 'Test',
                        'phone' => null,
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without product id' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => 'Test@email.it',
                        'country' => 'Test',
                        'address' => 'Test',
                        'phone' => '080808080',
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => null,
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without product name' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => 'Test@email.it',
                        'country' => 'Test',
                        'address' => 'Test',
                        'phone' => '080808080',
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => null,
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without product description' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'company_business_name' => 'Test',
                        'company_email' => 'Test@email.it',
                        'company_country' => 'Test',
                        'company_address' => 'Test',
                        'company_phone' => '080808080',
                        'company_vat_number' => '13346678',
                        'private_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => null,
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without product price' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'company_business_name' => 'Test',
                        'company_email' => 'Test@email.it',
                        'company_country' => 'Test',
                        'company_address' => 'Test',
                        'company_phone' => '080808080',
                        'company_vat_number' => '13346678',
                        'private_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => null,
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without product vat' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'company_business_name' => 'Test',
                        'company_email' => 'Test@email.it',
                        'company_country' => 'Test',
                        'company_address' => 'Test',
                        'company_phone' => '080808080',
                        'company_vat_number' => '13346678',
                        'private_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => null,
                        'total' => [10, 20, 30],
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without product total' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'company_business_name' => 'Test',
                        'company_email' => 'Test@email.it',
                        'company_country' => 'Test',
                        'company_address' => 'Test',
                        'company_phone' => '080808080',
                        'company_vat_number' => '13346678',
                        'private_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => null,
                        'quantity' => [10, 20, 30],
                    ],
                    'valid' => false,
                ],

                'without product quantity' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => 'Test@email.it',
                        'country' => 'Test',
                        'address' => 'Test',
                        'phone' => '080808080',
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => null,
                    ],
                    'valid' => false,
                ],

                'without date' => [
                    'data' => [
                        'type' => 'ingoing',
                        'data' => null,
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => 'Test@email.it',
                        'country' => 'Test',
                        'address' => 'Test',
                        'phone' => '080808080',
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => 1,
                    ],
                    'valid' => false,
                ],

                'without type' => [
                    'data' => [
                        'type' => null,
                        'data' => today()->format('d-m-Y'),
                        'company_id' => 1,
                        'business_name' => 'Test',
                        'email' => 'Test@email.it',
                        'country' => 'Test',
                        'address' => 'Test',
                        'phone' => '080808080',
                        'vat_number' => '13346678',
                        'contact_name' => 'Test',
                        'id' => [1, 2, 3],
                        'name' => ['Test', 'Test', 'Test'],
                        'description' => ['Test', 'Test', 'Test'],
                        'price' => [10, 20, 30],
                        'vat' => [10, 20, 30],
                        'total' => [10, 20, 30],
                        'quantity' => 1,
                    ],
                    'valid' => false,
                ],
            ];
    }
);
